version: '3'
services:
  api:
    image: debt-angel-api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: debt-angel-api
    networks:
      - backend
    command: sh

  mongo:
    image: mongo
    ports:
      - "27018:27017"

networks:
  backend:
    driver: bridge